theme: jekyll-theme-minimal
title: Julia Aronow's Portfolio
description: This page is designed to give you an overview of the projects I have worked on, as well as a glimpse into what I enjoy doing in my free time.